<?php

namespace NinjaPortal\Shadow\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use NinjaPortal\Shadow\Services\Portal\ProductCatalogService;
use Symfony\Component\HttpFoundation\Response;

class ProductsController extends Controller
{
    public function index(Request $request, ProductCatalogService $catalog)
    {
        $user = $this->shadowUser($request);
        $scope = $request->query('scope', $user ? 'mine' : 'public');

        return view('shadow-theme::pages.products.index', [
            'products' => $catalog->paginate([
                'scope' => $scope,
                'category' => $request->query('category'),
                'page' => $request->integer('page', 1),
                'per_page' => config('shadow-theme.catalog.per_page', 12),
            ], $user),
            'categories' => $catalog->categories(),
            'scope' => $user ? (string) $scope : 'public',
        ]);
    }

    public function show(Request $request, string $slug, ProductCatalogService $catalog)
    {
        $user = $this->shadowUser($request);
        $scope = $request->query('scope', $user ? 'mine' : 'public');

        return view('shadow-theme::pages.products.show', [
            'product' => $catalog->findVisibleBySlugOrFail($slug, $user, is_string($scope) ? $scope : null),
            'scope' => $user ? (string) $scope : 'public',
        ]);
    }

    public function spec(Request $request, string $slug, ProductCatalogService $catalog): Response
    {
        $user = $this->shadowUser($request);
        $scope = $request->query('scope', $user ? 'mine' : 'public');
        $product = $catalog->findVisibleBySlugOrFail($slug, $user, is_string($scope) ? $scope : null);
        $swaggerValue = trim((string) ($product->swagger_url ?? ''));

        abort_if($swaggerValue === '', 404);

        if (str_starts_with($swaggerValue, 'http://') || str_starts_with($swaggerValue, 'https://')) {
            try {
                $upstream = Http::timeout(20)->get($swaggerValue);
            } catch (\Throwable $exception) {
                return $this->fallbackSpecResponse($product->name ?? $product->slug ?? 'API Product', $exception->getMessage());
            }

            if (! $upstream->successful()) {
                return $this->fallbackSpecResponse(
                    $product->name ?? $product->slug ?? 'API Product',
                    sprintf('Unable to load the upstream specification (HTTP %s).', $upstream->status())
                );
            }

            if (! $this->looksLikeApiSpec($upstream->body(), $upstream->header('Content-Type', ''))) {
                return $this->fallbackSpecResponse(
                    $product->name ?? $product->slug ?? 'API Product',
                    'The configured specification source responded successfully, but it did not contain a valid OpenAPI/Swagger document.'
                );
            }

            return response(
                $upstream->body(),
                200,
                [
                    'Content-Type' => $upstream->header('Content-Type', $this->detectSpecMimeType($swaggerValue)),
                    'Cache-Control' => 'public, max-age=300',
                ]
            );
        }

        $disk = \NinjaPortal\Portal\Models\ApiProduct::$STORAGE_DISK;
        if (! Storage::disk($disk)->exists($swaggerValue)) {
            return $this->fallbackSpecResponse(
                $product->name ?? $product->slug ?? 'API Product',
                'The stored specification file could not be found.'
            );
        }

        $contents = Storage::disk($disk)->get($swaggerValue);
        $mimeType = Storage::disk($disk)->mimeType($swaggerValue) ?: $this->detectSpecMimeType($swaggerValue);

        if (! $this->looksLikeApiSpec($contents, $mimeType)) {
            return $this->fallbackSpecResponse(
                $product->name ?? $product->slug ?? 'API Product',
                'The stored specification file does not appear to be a valid OpenAPI/Swagger document.'
            );
        }

        return response(
            $contents,
            200,
            [
                'Content-Type' => $mimeType,
                'Cache-Control' => 'public, max-age=300',
            ]
        );
    }

    private function detectSpecMimeType(string $path): string
    {
        $normalized = strtolower($path);

        if (str_ends_with($normalized, '.yaml') || str_ends_with($normalized, '.yml')) {
            return 'application/yaml';
        }

        return 'application/json';
    }

    private function fallbackSpecResponse(string $title, string $message): Response
    {
        return response()->json([
            'openapi' => '3.0.3',
            'info' => [
                'title' => $title,
                'version' => '0.0.1-preview',
                'description' => 'Preview spec generated by Shadow Theme because the configured API definition could not be loaded. '.$message,
            ],
            'servers' => [
                ['url' => 'https://api.example.com'],
            ],
            'paths' => [
                '/payments' => [
                    'get' => [
                        'summary' => 'List payments',
                        'description' => 'Preview operation used to demonstrate Swagger theming in the portal.',
                        'responses' => [
                            '200' => [
                                'description' => 'Payment list returned successfully.',
                            ],
                        ],
                    ],
                    'post' => [
                        'summary' => 'Create payment',
                        'requestBody' => [
                            'required' => true,
                            'content' => [
                                'application/json' => [
                                    'schema' => [
                                        'type' => 'object',
                                        'properties' => [
                                            'amount' => ['type' => 'number', 'example' => 125.50],
                                            'currency' => ['type' => 'string', 'example' => 'USD'],
                                        ],
                                    ],
                                ],
                            ],
                        ],
                        'responses' => [
                            '201' => [
                                'description' => 'Payment created.',
                            ],
                        ],
                    ],
                ],
                '/payments/{paymentId}' => [
                    'delete' => [
                        'summary' => 'Cancel payment',
                        'parameters' => [
                            [
                                'name' => 'paymentId',
                                'in' => 'path',
                                'required' => true,
                                'schema' => ['type' => 'string'],
                            ],
                        ],
                        'responses' => [
                            '204' => [
                                'description' => 'Payment cancelled.',
                            ],
                        ],
                    ],
                ],
            ],
        ]);
    }

    private function looksLikeApiSpec(string $contents, string $contentType): bool
    {
        $trimmed = trim($contents);
        if ($trimmed === '') {
            return false;
        }

        if (str_contains(strtolower($contentType), 'json') || str_starts_with($trimmed, '{')) {
            $decoded = json_decode($contents, true);

            if (! is_array($decoded)) {
                return false;
            }

            $version = $decoded['openapi'] ?? $decoded['swagger'] ?? null;

            return is_string($version) && $this->isSupportedSpecVersion($version);
        }

        if (preg_match('/^swagger\s*:\s*[\"\']?2\.0[\"\']?/mi', $contents) === 1) {
            return true;
        }

        if (preg_match('/^openapi\s*:\s*[\"\']?(3\.[0-2]\.\d+)[\"\']?/mi', $contents) === 1) {
            return true;
        }

        return false;
    }

    private function isSupportedSpecVersion(string $version): bool
    {
        $normalized = trim($version);

        if ($normalized === '2.0') {
            return true;
        }

        return preg_match('/^3\.[0-2]\.\d+$/', $normalized) === 1;
    }
}
